In [1]:
import re
import os
from itertools import islice
from itertools import permutations
from itertools import combinations
import pandas as pd

In [2]:
#Read file and pass its lines to list
with open('outfile-cortado.txt','r') as origin_file:
    #Create an empty list
    file_rows = []
    for rows in origin_file:
        file_rows.append(rows)
    print(file_rows)

['  =============================================\n', '  3Rmangle                                     \n', '  =============================================\n', '  MIGRATION RATE AND POPULATION SIZE ESTIMATION\n', '  using Markov Chain Monte Carlo simulation\n', '  =============================================\n', '  Version 3.6.11\n', '\n', '  Program started at Fri Jan  3 18:05:12 2020\n', '         finished at Mon Feb 10 12:50:31 2020\n', '     \n', '\n', '\n', 'Options in use:\n', '---------------\n', '\n', 'Analysis strategy is MAXIMUM LIKELIHOOD\n', '\n', '\n', '\n', 'Datatype: Allelic data\n', 'Missing data is not included\n', '\n', 'Inheritance scalers in use for Thetas (specified scalars=1)\n', '1.00 1.00 1.00 1.00 1.00 \n', '1.00 \n', '[Each Theta uses the (true) ineritance scalar of the first locus as a reference]\n', '\n', '\n', 'Pseudo-random number generator: Mersenne-Twister                                \n', 'Random number seed (with internal timer)            515960483\n', '\n', 'Start parameters:\n', '   First genealogy was started using a random tree\n', '   Theta values were generated  from an FST-calculation\n', '   M values were generated from the FST-calculation\n', '\n', 'Migration model:\n', '   Migration matrix model with variable Theta  \n', '   Geographic distance matrix between locations\n', '      RLT               -   128.000 340.000 631.000 689.000 917.000 1127.000 1294.000 1512.000 1667.000 1932.000 2049.000 2141.000 2242.000 \n', '      RCS            128.000    -   212.000 503.000 561.000 789.000 999.000 1166.000 1384.000 1539.000 1804.000 1921.000 2013.000 2114.000 \n', '      RLA            340.000 212.000    -   291.000 349.000 577.000 787.000 954.000 1172.000 1327.000 1592.000 1709.000 1801.000 1902.000 \n', '      RVH            631.000 503.000 291.000    -   58.000 286.000 344.000 572.000 782.000 949.000 1167.000 1322.000 1587.000 1704.000 \n', '      RPC            689.000 561.000 349.000 58.000    -   228.000 438.000 605.000 823.000 978.000 1243.000 1360.000 1452.000 1553.000 \n', '      RSB            917.000 789.000 577.000 286.000 228.000    -   210.000 377.000 595.000 750.000 1015.000 1132.000 1224.000 1325.000 \n', '      RIA            1127.000 999.000 787.000 344.000 438.000 210.000    -   167.000 385.000 540.000 805.000 922.000 1014.000 1115.000 \n', '      RPT            1294.000 1166.000 954.000 572.000 605.000 377.000 167.000    -   218.000 373.000 638.000 755.000 847.000 948.000 \n', '      RCH            1512.000 1384.000 1172.000 782.000 823.000 595.000 385.000 218.000    -   155.000 420.000 537.000 629.000 730.000 \n', '      RPM            1667.000 1539.000 1327.000 949.000 978.000 750.000 540.000 373.000 155.000    -   265.000 382.000 474.000 575.000 \n', '      RMA            1932.000 1804.000 1592.000 1167.000 1243.000 1015.000 805.000 638.000 420.000 265.000    -   117.000 209.000 310.000 \n', '      RBE            2049.000 1921.000 1709.000 1322.000 1360.000 1132.000 922.000 755.000 537.000 382.000 117.000    -   92.000 193.000 \n', '      RDG            2141.000 2013.000 1801.000 1587.000 1452.000 1224.000 1014.000 847.000 629.000 474.000 209.000 92.000    -   101.000 \n', '      RPG            2242.000 2114.000 1902.000 1704.000 1553.000 1325.000 1115.000 948.000 730.000 575.000 310.000 193.000 101.000    -   \n', '      \n', '\n', 'Mutation rate is constant for all loci\n', '\n', 'Markov chain settings:\n', '   Short chains (short-chains):                           20\n', '      Trees sampled (short-inc*samples):             1000000\n', '      Trees recorded (short-sample):                    2000\n', '   Long chains (long-chains):                              3\n', '      Trees sampled (long-inc*samples):              2500000\n', '      Trees recorded (long-sample):                     5000\n', '   Static heating scheme\n', '      4 chains with  temperatures\n', '       1.00, 1.50, 3.00,1000000.00\n', '      Swapping interval is 1\n', '   Burn-in per chain:                            25000000\n', '\n', 'Print options:\n', '   Data file:                                         infile\n', '   Output file (ASCII text):                         outfile\n', '   Output file (PDF):                            outfile.pdf\n', '   Print data:                                           Yes\n', '   Print genealogies:                                     No\n', '   Plot data: No                                            \n', '   Profile likelihood: Yes, tables and summary             \n', '             Percentile method\n', '             with df=1 and for Theta and M=m/mu\n', '\n', '\n', '\n', '\n', 'Summary of data:\n', 'Title:                                              3Rmangle\n', 'Data file:                                            infile\n', 'Datatype:                                       Allelic data\n', 'Number of loci:                                            6\n', '\n', 'Population                   Locus   Gene copies    \n', '                                     ---------------\n', '                                     data  (missing)\n', '----------------------------------------------------\n', '  1 RLT                          1     60 (0)\n', '  1                              2     60 (0)\n', '  1                              3     60 (0)\n', '  1                              4     60 (0)\n', '  1                              5     60 (0)\n', '  1                              6     60 (0)\n', '  2 RCS                          1     32 (0)\n', '  2                              2     32 (0)\n', '  2                              3     32 (0)\n', '  2                              4     32 (0)\n', '  2                              5     32 (0)\n', '  2                              6     32 (0)\n', '  3 RLA                          1     64 (0)\n', '  3                              2     64 (0)\n', '  3                              3     64 (0)\n', '  3                              4     64 (0)\n', '  3                              5     64 (0)\n', '  3                              6     64 (0)\n', '  4 RVH                          1     38 (0)\n', '  4                              2     38 (0)\n', '  4                              3     38 (0)\n', '  4                              4     38 (0)\n', '  4                              5     38 (0)\n', '  4                              6     38 (0)\n', '  5 RPC                          1     42 (0)\n', '  5                              2     42 (0)\n', '  5                              3     42 (0)\n', '  5                              4     42 (0)\n', '  5                              5     42 (0)\n', '  5                              6     42 (0)\n', '  6 RSB                          1     56 (0)\n', '  6                              2     56 (0)\n', '  6                              3     56 (0)\n', '  6                              4     56 (0)\n', '  6                              5     56 (0)\n', '  6                              6     56 (0)\n', '  7 RIA                          1     36 (0)\n', '  7                              2     36 (0)\n', '  7                              3     36 (0)\n', '  7                              4     36 (0)\n', '  7                              5     36 (0)\n', '  7                              6     36 (0)\n', '  8 RPT                          1     54 (0)\n', '  8                              2     54 (0)\n', '  8                              3     54 (0)\n', '  8                              4     54 (0)\n', '  8                              5     54 (0)\n', '  8                              6     54 (0)\n', '  9 RCH                          1     16 (0)\n', '  9                              2     16 (0)\n', '  9                              3     16 (0)\n', '  9                              4     16 (0)\n', '  9                              5     16 (0)\n', '  9                              6     16 (0)\n', ' 10 RPM                          1     56 (0)\n', ' 10                              2     56 (0)\n', ' 10                              3     56 (0)\n', ' 10                              4     56 (0)\n', ' 10                              5     56 (0)\n', ' 10                              6     56 (0)\n', ' 11 RMA                          1     16 (0)\n', ' 11                              2     16 (0)\n', ' 11                              3     16 (0)\n', ' 11                              4     16 (0)\n', ' 11                              5     16 (0)\n', ' 11                              6     16 (0)\n', ' 12 RBE                          1     16 (0)\n', ' 12                              2     16 (0)\n', ' 12                              3     16 (0)\n', ' 12                              4     16 (0)\n', ' 12                              5     16 (0)\n', ' 12                              6     16 (0)\n', ' 13 RDG                          1     46 (0)\n', ' 13                              2     46 (0)\n', ' 13                              3     46 (0)\n', ' 13                              4     46 (0)\n', ' 13                              5     46 (0)\n', ' 13                              6     46 (0)\n', ' 14 RPG                          1     34 (0)\n', ' 14                              2     34 (0)\n', ' 14                              3     34 (0)\n', ' 14                              4     34 (0)\n', ' 14                              5     34 (0)\n', ' 14                              6     34 (0)\n', '    Total of all populations     1    566 (0)\n', '                                 2    566 (0)\n', '                                 3    566 (0)\n', '                                 4    566 (0)\n', '                                 5    566 (0)\n', '                                 6    566 (0)\n', '\n', '===============================================================================\n', 'Summary of profile likelihood percentiles of all parameters\n', '===============================================================================\n', '\n', '\n', 'Parameter                          Lower percentiles\n', '            --------------------------------------------------------------------\n', '                0.005         0.025         0.050         0.250         MLE\n', '--------------------------------------------------------------------------------\n', 'Theta_1         0.424302      0.436666      0.443169      0.464086      0.479349  \n', 'Theta_2         0.299830      0.311888      0.318304      0.339206      0.354828  \n', 'Theta_3         0.468880      0.483731      0.491571      0.516801      0.535359  \n', 'Theta_4         0.361483      0.374756      0.381804      0.404668      0.421622  \n', 'Theta_5         0.472815      0.491434      0.501313      0.533496      0.557550  \n', 'Theta_6         0.617537      0.637129      0.647487      0.680819      0.705338  \n', 'Theta_7         0.380955      0.396905      0.405412      0.433235      0.454031  \n', 'Theta_8         0.489382      0.505043      0.513297      0.539956      0.559567  \n', 'Theta_9         0.830797      0.888313      0.919882      1.026782      1.111256  \n', 'Theta_10        0.578636      0.598668      0.609279      0.643571      0.668999  \n', 'Theta_11        0.328612      0.352193      0.365124      0.409267      0.444149  \n', 'Theta_12        0.275332      0.290882      0.299305      0.327335      0.348963  \n', 'Theta_13        0.647592      0.673326      0.687019      0.731629      0.764971  \n', 'Theta_14        0.498433      0.519675      0.531021      0.568002      0.595865  \n', '  M_21        144.188036    161.211053    170.453597    201.181520    224.517847  \n', '  M_31       4.97477e-11*  7.46165e-11*   8.7051e-11*  9.32682e-11*  9.94854e-11  \n', '  M_41        182.605054    223.807209    247.275161    329.915700    397.317557  \n', '  M_51        1.0077e-10*   1.5115e-10*   1.7634e-10*  1.88935e-10*   2.0153e-10  \n', '  M_61       1.34102e-10*  2.01148e-10*  2.34671e-10*  2.51433e-10*  2.68194e-10  \n', '  M_71         61.100873     90.871672    109.604802    184.611118    253.437138  \n', '  M_81       1.89217e-10*   2.8382e-10*  3.31122e-10*  3.54773e-10*  3.78424e-10  \n', '  M_91        265.138865    340.702634    384.775498    545.089765    680.030551  \n', '  M_101      2.43747e-10*  3.65615e-10*  4.26549e-10*  4.57016e-10*  4.87483e-10  \n', '  M_111      2.82487e-10*  4.23726e-10*  4.94345e-10*  5.29654e-10*  5.64964e-10  \n', '  M_121      2.99591e-10*  4.49382e-10*  5.24277e-10*  5.61725e-10*  5.99172e-10  \n', '  M_131      3.13041e-10*  4.69556e-10*  5.47814e-10*  5.86942e-10*  6.26071e-10  \n', '  M_141       221.093845    303.227141    352.768131    541.030342    705.845978  \n', '  M_12        119.539184    136.443597    145.679244    176.904406    200.998563  \n', '  M_32         89.301793    107.733215    118.115290    154.414023    183.670673  \n', '  M_42       3.85575e-08*  5.78362e-08*  6.74756e-08*  7.22952e-08*  7.71149e-08  \n', '  M_52          0.410678      1.734883      3.210354     14.193828     30.377207  \n', '  M_62       6.04808e-08*  9.07211e-08*  1.05841e-07*  1.13401e-07*  1.20962e-07  \n', '  M_72       7.65783e-08*  1.14867e-07*  1.34012e-07*  1.43584e-07*  1.53157e-07  \n', '  M_82       8.93797e-08*  1.34069e-07*  1.56414e-07*  1.67587e-07*  1.78759e-07  \n', '  M_92        1.0609e-07*  1.59136e-07*  1.85658e-07*   1.9892e-07*  2.12181e-07  \n', '  M_102      1.17972e-07*  1.76958e-07*  2.06451e-07*  2.21197e-07*  2.35944e-07  \n', '  M_112      1.38285e-07*  2.07428e-07*     2.42e-07*  2.59285e-07*  2.76571e-07  \n', '  M_122      1.47254e-07*  2.20881e-07*  2.57695e-07*  2.76101e-07*  2.94508e-07  \n', '  M_132      1.54306e-07*   2.3146e-07*  2.70036e-07*  2.89324e-07*  3.08613e-07  \n', '  M_142      1.62048e-07*  2.43073e-07*  2.83585e-07*  3.03841e-07*  3.24097e-07  \n', '  M_13        747.459063    828.619720    872.402515       1016.83       1126.52  \n', '  M_23       8.51236e-11*   1.2768e-10*  1.48959e-10*  1.59598e-10*  1.70237e-10  \n', '  M_43        123.831069    153.215733    169.982068    229.558917    278.534904  \n', '  M_53        148.512016    183.753379    203.861435    275.312631    334.050091  \n', '  M_63        573.027223    664.173452    714.502425    885.523992        1019.6  \n', '  M_73       3.15789e-10*  4.73679e-10*  5.52623e-10*  5.92096e-10*  6.31568e-10  \n', '  M_83        3.8278e-10*  5.74165e-10*  6.69858e-10*  7.17704e-10*  7.65551e-10  \n', '  M_93       4.70229e-10*  7.05339e-10*  8.22894e-10*  8.81672e-10*  9.40449e-10  \n', '  M_103      5.32406e-10*  7.98604e-10*  9.31703e-10*  9.98252e-10*   1.0648e-09  \n', '  M_113      6.38707e-10*  9.58056e-10*  1.11773e-09*  1.19757e-09*   1.2774e-09  \n', '  M_123       6.8564e-10*  1.02846e-09*  1.19986e-09*  1.28557e-09*  1.37127e-09  \n', '  M_133      7.22544e-10*  1.08381e-09*  1.26445e-09*  1.35476e-09*  1.44508e-09  \n', '  M_143      7.63059e-10*  1.14458e-09*  1.33535e-09*  1.43073e-09*  1.52611e-09  \n', '  M_14        544.100641    608.337831    643.215027    759.168355    847.229130  \n', '  M_24          0.234115      0.989002      1.830121      8.091453     17.317086  \n', '  M_34         27.423507     36.627032     42.109587     62.540093     80.147474  \n', '  M_54         19.696398     23.330588     25.363443     32.363290     37.938607  \n', '  M_64          0.133115      0.562335      1.040586      4.600707      9.846296  \n', '  M_74       4.89716e-10*  7.34569e-10*  8.56995e-10*  9.18208e-10*  9.79422e-10  \n', '  M_84        8.1426e-10*  1.22138e-09*  1.42495e-09*  1.52673e-09*  1.62851e-09  \n', '  M_94       1.11318e-09*  1.66977e-09*  1.94806e-09*  2.08721e-09*  2.22635e-09  \n', '  M_104       1.3509e-09*  2.02634e-09*  2.36406e-09*  2.53292e-09*  2.70178e-09  \n', '  M_114      1.66121e-09*  2.49181e-09*  2.90711e-09*  3.11476e-09*  3.32241e-09  \n', '  M_124      1.88184e-09*  2.82276e-09*  3.29322e-09*  3.52845e-09*  3.76368e-09  \n', '  M_134      2.25906e-09*  3.38858e-09*  3.95334e-09*  4.23572e-09*  4.51811e-09  \n', '  M_144       2.4256e-09*   3.6384e-09*  4.24479e-09*  4.54799e-09*  4.85119e-09  \n', '  M_15        165.415140    212.669624    240.185875    340.275753    424.524068  \n', '  M_25          0.467320      1.974163      3.653136     16.151484     34.566925  \n', '  M_35         16.779156     26.701641     33.189237     60.222092     86.016802  \n', '  M_45         92.345538    103.094175    108.932520    128.267022    142.950614  \n', '  M_65        199.916590    230.907697    248.002178    305.857942    351.215248  \n', '  M_75       8.11304e-11*  1.21691e-10*  1.41971e-10*  1.52111e-10*  1.62251e-10  \n', '  M_85       1.12041e-10*  1.68057e-10*  1.96065e-10*  2.10069e-10*  2.24073e-10  \n', '  M_95       1.52392e-10*  2.28583e-10*  2.66678e-10*  2.85726e-10*  3.04774e-10  \n', '  M_105      1.81082e-10*  2.71618e-10*  3.16886e-10*   3.3952e-10*  3.62154e-10  \n', '  M_115      2.30134e-10*  3.45196e-10*  4.02728e-10*  4.31493e-10*  4.60259e-10  \n', '  M_125      2.51788e-10*  3.77678e-10*  4.40622e-10*  4.72095e-10*  5.03567e-10  \n', '  M_135      2.68813e-10*  4.03214e-10*  4.70415e-10*  5.04016e-10*  5.37616e-10  \n', '  M_145      2.87508e-10*  4.31257e-10*  5.03131e-10*  5.39069e-10*  5.75006e-10  \n', '  M_16       3.10009e-11*  4.64963e-11*   5.4244e-11*  5.81179e-11*  6.19917e-11  \n', '  M_26         25.049990     34.355714     39.968721     61.298879     79.972534  \n', '  M_36       1.95261e-11*  2.92842e-11*  3.41632e-11*  3.66027e-11*  3.90423e-11  \n', '  M_46         37.944613     45.190925     49.246832     63.327434     74.542510  \n', '  M_56          2.576007      4.099349      5.095353      9.245551     13.205665  \n', '  M_76       7.13932e-12*   1.0704e-11*  1.24863e-11*  1.33775e-11*  1.42686e-11  \n', '  M_86          4.259451      6.778311      8.425211     15.287602     21.835685  \n', '  M_96       2.01336e-11*  3.01954e-11*  3.52263e-11*  3.77418e-11*  4.02573e-11  \n', '  M_106      2.53648e-11*  3.80422e-11*  4.43809e-11*  4.75503e-11*  5.07196e-11  \n', '  M_116         0.198694      0.839371      1.553233      6.867256     14.697096  \n', '  M_126      3.82408e-11*  5.73562e-11*  6.69139e-11*  7.16927e-11*  7.64716e-11  \n', '  M_136      4.13477e-11*  6.20166e-11*   7.2351e-11*  7.75182e-11*  8.26854e-11  \n', '  M_146      4.47561e-11*  6.71291e-11*  7.83156e-11*  8.39089e-11*  8.95021e-11  \n', '  M_17         46.020585     81.767579    106.483341    216.715736    328.684074  \n', '  M_27       2.14217e-09*  3.21325e-09*  3.74879e-09*  4.01656e-09*  4.28433e-09  \n', '  M_37           1261.23       1443.62       1543.57       1880.32       2142.23  \n', '  M_47         91.439293    122.219944    140.525006    208.738026    267.525247  \n', '  M_57       9.39243e-10*  1.40886e-09*  1.64367e-09*  1.76107e-09*  1.87848e-09  \n', '  M_67         34.301058     48.683591     57.513086     91.778762    122.490961  \n', '  M_87        280.004729    319.601079    341.234361    414.375174    470.812550  \n', '  M_97       8.25597e-10*  1.23839e-09*  1.44479e-09*  1.54799e-09*  1.65118e-09  \n', '  M_107       269.683449    337.322034    376.187146    514.965603    629.953468  \n', '  M_117      1.72619e-09*  2.58927e-09*  3.02082e-09*  3.23659e-09*  3.45236e-09  \n', '  M_127      1.97706e-09*  2.96559e-09*  3.45986e-09*  3.70699e-09*  3.95412e-09  \n', '  M_137      2.17434e-09*   3.2615e-09*  3.80508e-09*  4.07687e-09*  4.34866e-09  \n', '  M_147      2.39091e-09*  3.58635e-09*  4.18408e-09*  4.48294e-09*   4.7818e-09  \n', '  M_18       3.34044e-10*  5.01061e-10*   5.8457e-10*  6.26324e-10*  6.68078e-10  \n', '  M_28       3.01003e-10*  4.51499e-10*  5.26747e-10*  5.64371e-10*  6.01996e-10  \n', '  M_38       2.46278e-10*  3.69412e-10*  4.30979e-10*  4.61762e-10*  4.92546e-10  \n', '  M_48        1.4767e-10*    2.215e-10*  2.58414e-10*  2.76872e-10*  2.95329e-10  \n', '  M_58         33.773020     42.765633     47.967095     66.712003     82.366352  \n', '  M

In [3]:
#Find words -> function
def find_groups(substr, infile):
    with open(infile) as origin:
        for line in origin:
            if substr in line:
                print(line)
                
find_groups('Population','outfile-cortado.txt')
find_groups('Total of','outfile-cortado.txt')

Population                   Locus   Gene copies

    Total of all populations     1    566 (0)

In [4]:
#find percentiles -> function
def find_percentiles(substr, infile):
    with open(infile) as origin:
        for line in origin:
            if substr in line:
                print(line)

find_percentiles('Lower percentiles','outfile-cortado.txt')
find_percentiles('Upper percentiles','outfile-cortado.txt')

Parameter                          Lower percentiles

Parameter                          Upper percentiles

In [6]:
#find indexes in file_rows list
start_index_group = file_rows.index('Population                   Locus   Gene copies    \n')
end_index_group = file_rows.index('    Total of all populations     1    566 (0)\n')
index_lower = file_rows.index('Parameter                          Lower percentiles\n')
index_upper = file_rows.index('Parameter                          Upper percentiles\n')
print(start_index_group, end_index_group, index_lower, index_upper)

91 179 191 395

In [14]:
#This cell must be executed once
#Group csv file
groups_filename = 'groups'
index_1 = 0

while os.path.exists(f"{groups_filename}{index_1}.csv"):
    index_1 += 1

with open('outfile-cortado.txt', 'r') as origin_file:
    for line in islice(origin_file, start_index_group + 4, end_index_group):
        with open(f"{groups_filename}{index_1}.csv", 'a') as group_file:
            print(re.sub("\s+",",", line.strip()))
            group_file.write(re.sub("\s+",",", line.strip()) + '\n')

1,RLT,1,60,(0)
1,2,60,(0)
1,3,60,(0)
1,4,60,(0)
1,5,60,(0)
1,6,60,(0)
2,RCS,1,32,(0)
2,2,32,(0)
2,3,32,(0)
2,4,32,(0)
2,5,32,(0)
2,6,32,(0)
3,RLA,1,64,(0)
3,2,64,(0)
3,3,64,(0)
3,4,64,(0)
3,5,64,(0)
3,6,64,(0)
4,RVH,1,38,(0)
4,2,38,(0)
4,3,38,(0)
4,4,38,(0)
4,5,38,(0)
4,6,38,(0)
5,RPC,1,42,(0)
5,2,42,(0)
5,3,42,(0)
5,4,42,(0)
5,5,42,(0)
5,6,42,(0)
6,RSB,1,56,(0)
6,2,56,(0)
6,3,56,(0)
6,4,56,(0)
6,5,56,(0)
6,6,56,(0)
7,RIA,1,36,(0)
7,2,36,(0)
7,3,36,(0)
7,4,36,(0)
7,5,36,(0)
7,6,36,(0)
8,RPT,1,54,(0)
8,2,54,(0)
8,3,54,(0)
8,4,54,(0)
8,5,54,(0)
8,6,54,(0)
9,RCH,1,16,(0)
9,2,16,(0)
9,3,16,(0)
9,4,16,(0)
9,5,16,(0)
9,6,16,(0)
10,RPM,1,56,(0)
10,2,56,(0)
10,3,56,(0)
10,4,56,(0)
10,5,56,(0)
10,6,56,(0)
11,RMA,1,16,(0)
11,2,16,(0)
11,3,16,(0)
11,4,16,(0)
11,5,16,(0)
11,6,16,(0)
12,RBE,1,16,(0)
12,2,16,(0)
12,3,16,(0)
12,4,16,(0)
12,5,16,(0)
12,6,16,(0)
13,RDG,1,46,(0)
13,2,46,(0)
13,3,46,(0)
13,4,46,(0)
13,5,46,(0)
13,6,46,(0)
14,RPG,1,34,(0)
14,2,34,(0)
14,3,34,(0)
14,4,34,(0)
14,5,34,(0)
14,6,34,(0)

In [15]:
#Groups dataframe with unnecessary data
groups_df = pd.read_csv(f"{groups_filename}{index_1}.csv", header=None)
groups_df

     0    1   2    3    4
0    1  RLT   1   60  (0)
1    1    2  60  (0)  NaN
2    1    3  60  (0)  NaN
3    1    4  60  (0)  NaN
4    1    5  60  (0)  NaN
..  ..  ...  ..  ...  ...
79  14    2  34  (0)  NaN
80  14    3  34  (0)  NaN
81  14    4  34  (0)  NaN
82  14    5  34  (0)  NaN
83  14    6  34  (0)  NaN

[84 rows x 5 columns]

In [16]:
#This cell must be executed once
#Remove NaN values
groups_df = groups_df.dropna()
#Remove 'Locus' column
groups_df = groups_df.drop(2,1)
#Remove 'missing (0)' column
groups_df = groups_df.drop(4,1)
groups_df

     0    1   3
0    1  RLT  60
6    2  RCS  32
12   3  RLA  64
18   4  RVH  38
24   5  RPC  42
30   6  RSB  56
36   7  RIA  36
42   8  RPT  54
48   9  RCH  16
54  10  RPM  56
60  11  RMA  16
66  12  RBE  16
72  13  RDG  46
78  14  RPG  34

In [10]:
#Get total of groups and its n-value
#Change data types str -> int
total_per_group = list(map(int, (groups_df[3])))
print(total_per_group, len(total_per_group))

[60, 32, 64, 38, 42, 56, 36, 54, 16, 56, 16, 16, 46, 34] 14

In [11]:
#Start and end lower percentiles
range_lower_start = index_lower + 4 + len(total_per_group)
range_lower_end = range_lower_start + len(list(permutations(range(len(total_per_group)),2)))
print(range_lower_start, range_lower_end)

209 391

In [12]:
#Start and end upper percentiles
range_upper_start = index_upper + 4 + len(total_per_group)
range_upper_end = range_upper_start + len(list(permutations(range(len(total_per_group)),2)))
print(range_upper_start, range_upper_end)

413 595

In [17]:
#This cell must be executed once
#lower percentiles csv
lower_percentiles_filename = 'lower_percentiles'
index_2 = 0

while os.path.exists(f"{lower_percentiles_filename}{index_2}.csv"):
    index_2 += 1

with open('outfile-cortado.txt', 'r') as origin_file:
    for line in islice(origin_file, range_lower_start, range_lower_end):
        with open(f"{lower_percentiles_filename}{index_1}.csv",'a') as lower_file:
            print(re.sub("\s+", ",", line.strip()))
            lower_file.write(re.sub("\s+", ",", line.strip()) + '\n')

M_21,144.188036,161.211053,170.453597,201.181520,224.517847
M_31,4.97477e-11*,7.46165e-11*,8.7051e-11*,9.32682e-11*,9.94854e-11
M_41,182.605054,223.807209,247.275161,329.915700,397.317557
M_51,1.0077e-10*,1.5115e-10*,1.7634e-10*,1.88935e-10*,2.0153e-10
M_61,1.34102e-10*,2.01148e-10*,2.34671e-10*,2.51433e-10*,2.68194e-10
M_71,61.100873,90.871672,109.604802,184.611118,253.437138
M_81,1.89217e-10*,2.8382e-10*,3.31122e-10*,3.54773e-10*,3.78424e-10
M_91,265.138865,340.702634,384.775498,545.089765,680.030551
M_101,2.43747e-10*,3.65615e-10*,4.26549e-10*,4.57016e-10*,4.87483e-10
M_111,2.82487e-10*,4.23726e-10*,4.94345e-10*,5.29654e-10*,5.64964e-10
M_121,2.99591e-10*,4.49382e-10*,5.24277e-10*,5.61725e-10*,5.99172e-10
M_131,3.13041e-10*,4.69556e-10*,5.47814e-10*,5.86942e-10*,6.26071e-10
M_141,221.093845,303.227141,352.768131,541.030342,705.845978
M_12,119.539184,136.443597,145.679244,176.904406,200.998563
M_32,89.301793,107.733215,118.115290,154.414023,183.670673
M_42,3.85575e-08*,5.78362e-08*,6.74756e-08*,7.22952e-08*,7.71149e-08
M_52,0.410678,1.734883,3.210354,14.193828,30.377207
M_62,6.04808e-08*,9.07211e-08*,1.05841e-07*,1.13401e-07*,1.20962e-07
M_72,7.65783e-08*,1.14867e-07*,1.34012e-07*,1.43584e-07*,1.53157e-07
M_82,8.93797e-08*,1.34069e-07*,1.56414e-07*,1.67587e-07*,1.78759e-07
M_92,1.0609e-07*,1.59136e-07*,1.85658e-07*,1.9892e-07*,2.12181e-07
M_102,1.17972e-07*,1.76958e-07*,2.06451e-07*,2.21197e-07*,2.35944e-07
M_112,1.38285e-07*,2.07428e-07*,2.42e-07*,2.59285e-07*,2.76571e-07
M_122,1.47254e-07*,2.20881e-07*,2.57695e-07*,2.76101e-07*,2.94508e-07
M_132,1.54306e-07*,2.3146e-07*,2.70036e-07*,2.89324e-07*,3.08613e-07
M_142,1.62048e-07*,2.43073e-07*,2.83585e-07*,3.03841e-07*,3.24097e-07
M_13,747.459063,828.619720,872.402515,1016.83,1126.52
M_23,8.51236e-11*,1.2768e-10*,1.48959e-10*,1.59598e-10*,1.70237e-10
M_43,123.831069,153.215733,169.982068,229.558917,278.534904
M_53,148.512016,183.753379,203.861435,275.312631,334.050091
M_63,573.027223,664.173452,714.502425,885.523992,1019.6
M_73,3.15789e-10*,4.73679e-10*,5.52623e-10*,5.92096e-10*,6.31568e-10
M_83,3.8278e-10*,5.74165e-10*,6.69858e-10*,7.17704e-10*,7.65551e-10
M_93,4.70229e-10*,7.05339e-10*,8.22894e-10*,8.81672e-10*,9.40449e-10
M_103,5.32406e-10*,7.98604e-10*,9.31703e-10*,9.98252e-10*,1.0648e-09
M_113,6.38707e-10*,9.58056e-10*,1.11773e-09*,1.19757e-09*,1.2774e-09
M_123,6.8564e-10*,1.02846e-09*,1.19986e-09*,1.28557e-09*,1.37127e-09
M_133,7.22544e-10*,1.08381e-09*,1.26445e-09*,1.35476e-09*,1.44508e-09
M_143,7.63059e-10*,1.14458e-09*,1.33535e-09*,1.43073e-09*,1.52611e-09
M_14,544.100641,608.337831,643.215027,759.168355,847.229130
M_24,0.234115,0.989002,1.830121,8.091453,17.317086
M_34,27.423507,36.627032,42.109587,62.540093,80.147474
M_54,19.696398,23.330588,25.363443,32.363290,37.938607
M_64,0.133115,0.562335,1.040586,4.600707,9.846296
M_74,4.89716e-10*,7.34569e-10*,8.56995e-10*,9.18208e-10*,9.79422e-10
M_84,8.1426e-10*,1.22138e-09*,1.42495e-09*,1.52673e-09*,1.62851e-09
M_94,1.11318e-09*,1.66977e-09*,1.94806e-09*,2.08721e-09*,2.22635e-09
M_104,1.3509e-09*,2.02634e-09*,2.36406e-09*,2.53292e-09*,2.70178e-09
M_114,1.66121e-09*,2.49181e-09*,2.90711e-09*,3.11476e-09*,3.32241e-09
M_124,1.88184e-09*,2.82276e-09*,3.29322e-09*,3.52845e-09*,3.76368e-09
M_134,2.25906e-09*,3.38858e-09*,3.95334e-09*,4.23572e-09*,4.51811e-09
M_144,2.4256e-09*,3.6384e-09*,4.24479e-09*,4.54799e-09*,4.85119e-09
M_15,165.415140,212.669624,240.185875,340.275753,424.524068
M_25,0.467320,1.974163,3.653136,16.151484,34.566925
M_35,16.779156,26.701641,33.189237,60.222092,86.016802
M_45,92.345538,103.094175,108.932520,128.267022,142.950614
M_65,199.916590,230.907697,248.002178,305.857942,351.215248
M_75,8.11304e-11*,1.21691e-10*,1.41971e-10*,1.52111e-10*,1.62251e-10
M_85,1.12041e-10*,1.68057e-10*,1.96065e-10*,2.10069e-10*,2.24073e-10
M_95,1.52392e-10*,2.28583e-10*,2.66678e-10*,2.85726e-10*,3.04774e-10
M_105,1.81082e-10*,2.71618e-10*,3.16886e-10*,3.3952e-10*,3.62154e-10
M_115,2.30134e-10*,3.45196e-10*,4.02728e-10*,4.31493e-10*,4.60259e-10
M_125,2.51788e-10*,3.77678e-10*,4.40622e-10*,4.72095e-10*,5.03567e-10
M_135,2.68813e-10*,4.03214e-10*,4.70415e-10*,5.04016e-10*,5.37616e-10
M_145,2.87508e-10*,4.31257e-10*,5.03131e-10*,5.39069e-10*,5.75006e-10
M_16,3.10009e-11*,4.64963e-11*,5.4244e-11*,5.81179e-11*,6.19917e-11
M_26,25.049990,34.355714,39.968721,61.298879,79.972534
M_36,1.95261e-11*,2.92842e-11*,3.41632e-11*,3.66027e-11*,3.90423e-11
M_46,37.944613,45.190925,49.246832,63.327434,74.542510
M_56,2.576007,4.099349,5.095353,9.245551,13.205665
M_76,7.13932e-12*,1.0704e-11*,1.24863e-11*,1.33775e-11*,1.42686e-11
M_86,4.259451,6.778311,8.425211,15.287602,21.835685
M_96,2.01336e-11*,3.01954e-11*,3.52263e-11*,3.77418e-11*,4.02573e-11
M_106,2.53648e-11*,3.80422e-11*,4.43809e-11*,4.75503e-11*,5.07196e-11
M_116,0.198694,0.839371,1.553233,6.867256,14.697096
M_126,3.82408e-11*,5.73562e-11*,6.69139e-11*,7.16927e-11*,7.64716e-11
M_136,4.13477e-11*,6.20166e-11*,7.2351e-11*,7.75182e-11*,8.26854e-11
M_146,4.47561e-11*,6.71291e-11*,7.83156e-11*,8.39089e-11*,8.95021e-11
M_17,46.020585,81.767579,106.483341,216.715736,328.684074
M_27,2.14217e-09*,3.21325e-09*,3.74879e-09*,4.01656e-09*,4.28433e-09
M_37,1261.23,1443.62,1543.57,1880.32,2142.23
M_47,91.439293,122.219944,140.525006,208.738026,267.525247
M_57,9.39243e-10*,1.40886e-09*,1.64367e-09*,1.76107e-09*,1.87848e-09
M_67,34.301058,48.683591,57.513086,91.778762,122.490961
M_87,280.004729,319.601079,341.234361,414.375174,470.812550
M_97,8.25597e-10*,1.23839e-09*,1.44479e-09*,1.54799e-09*,1.65118e-09
M_107,269.683449,337.322034,376.187146,514.965603,629.953468
M_117,1.72619e-09*,2.58927e-09*,3.02082e-09*,3.23659e-09*,3.45236e-09
M_127,1.97706e-09*,2.96559e-09*,3.45986e-09*,3.70699e-09*,3.95412e-09
M_137,2.17434e-09*,3.2615e-09*,3.80508e-09*,4.07687e-09*,4.34866e-09
M_147,2.39091e-09*,3.58635e-09*,4.18408e-09*,4.48294e-09*,4.7818e-09
M_18,3.34044e-10*,5.01061e-10*,5.8457e-10*,6.26324e-10*,6.68078e-10
M_28,3.01003e-10*,4.51499e-10*,5.26747e-10*,5.64371e-10*,6.01996e-10
M_38,2.46278e-10*,3.69412e-10*,4.30979e-10*,4.61762e-10*,4.92546e-10
M_48,1.4767e-10*,2.215e-10*,2.58414e-10*,2.76872e-10*,2.95329e-10
M_58,33.773020,42.765633,47.967095,66.712003,82.366352
M_68,9.73327e-11*,1.45994e-10*,1.70325e-10*,1.8249e-10*,1.94655e-10
M_78,26.357425,30.659838,33.041647,41.167832,47.538536
M_98,4.533382,6.434242,7.601187,12.129893,16.188955
M_108,9.63002e-11*,1.44445e-10*,1.68518e-10*,1.80554e-10*,1.9259e-10
M_118,1.64707e-10*,2.47055e-10*,2.88229e-10*,3.08816e-10*,3.29404e-10
M_128,1.94909e-10*,2.92358e-10*,3.41083e-10*,3.65445e-10*,3.89808e-10
M_138,2.18657e-10*,3.27981e-10*,3.82643e-10*,4.09974e-10*,4.37305e-10
M_148,2.44729e-10*,3.67089e-10*,4.28269e-10*,4.58858e-10*,4.89448e-10
M_19,453.415467,551.190782,606.385895,800.628985,957.808022
M_29,1.49746e-09*,2.24618e-09*,2.62054e-09*,2.80772e-09*,2.9949e-09
M_39,38.620857,61.459602,76.392206,138.614169,197.986271
M_49,8.46124e-10*,1.26918e-09*,1.48071e-09*,1.58647e-09*,1.69224e-09
M_59,8.90484e-10*,1.33572e-09*,1.55834e-09*,1.66965e-09*,1.78096e-09
M_69,6.43813e-10*,9.65714e-10*,1.12666e-09*,1.20714e-09*,1.28762e-09
M_79,4.16603e-10*,6.249e-10*,7.29048e-10*,7.81122e-10*,8.33196e-10
M_89,47.295401,59.157434,65.973355,90.311455,110.477309
M_109,2.749551,4.885295,6.361966,12.947923,19.637595
M_119,7.450394,13.237570,17.238870,35.084685,53.211536
M_129,5.8106e-10*,8.71584e-10*,1.01685e-09*,1.08948e-09*,1.16211e-09
M_139,6.80583e-10*,1.02087e-09*,1.19101e-09*,1.27608e-09*,1.36116e-09
M_149,51.797983,73.517027,86.850436,138.594990,184.973441
M_110,7.65711e-08*,1.14857e-07*,1.33999e-07*,1.43571e-07*,1.53142e-07
M_210,513.249047,611.264617,666.125914,856.583926,1008.28
M_310,6.09537e-08*,9.14306e-08*,1.06669e-07*,1.14288e-07*,1.21907e-07
M_410,11.299379,29.674277,145.044844,215.549655,276.311983
M_510,4.49229e-08*,6.73844e-08*,7.86151e-08*,8.42305e-08*,8.98459e-08
M_610,3.45715e-08*,5.18572e-08*,6.05001e-08*,6.48215e-08*,6.9143e-08
M_710,523.618457,583.700621,616.131995,723.953900,805.839264
M_810,2.051684,4.515191,6.438478,16.188630,27.152495
M_910,7.11973e-09*,1.06796e-08*,1.24595e-08*,1.33495e-08*,1.42395e-08
M_1110,1.21724e-08*,1.82586e-08*,2.13017e-08*,2.28233e-08*,2.43448e-08
M_1210,5.840219,10.376673,13.513214,27.502200,41.711485
M_1310,88.629102,110.857930,123.630609,169.238933,207.028687
M_1410,2.64118e-08*,3.96176e-08*,4.62206e-08*,4.95221e-08*,5.28235e-08
M_111,1.54961e-10*,2.32437e-10*,2.71175e-10*,2.90544e-10*,3.09913e-10
M_211,1.44707e-10*,2.17055e-10*,2.53229e-10*,2.71316e-10*,2.89403e-10
M_311,1.27705e-10*,1.91552e-10*,2.23476e-10*,2.39437e-10*,2.55399e-10
M_411,9.36216e-11*,1.40427e-10*,1.6383e-10*,1.75532e-10*,1.87233e-10
M_511,9.97164e-11*,1.4957e-10*,1.74496e-10*,1.8696e-10*,1.99423e-10
M_611,8.14322e-11*,1.22143e-10*,1.42499e-10*,1.52677e-10*,1.62854e-10
M_711,46.031483,73.252559,91.050453,165.211656,235.976162
M_811,36.481991,58.055900,72.161520,130.937561,187.021570
M_911,3.37282e-11*,5.05873e-11*,5.90168e-11*,6.32316e-11*,6.74464e-11
M_1011,75.718477,97.298012,109.884361,155.666981,194.203432
M_1211,9.44348e-12*,1.41602e-11*,1.65186e-11*,1.76978e-11*,1.8877e-11
M_1311,119.150972,143.743108,157.595397,206.027003,245.062707
M_1411,2.49102e-11*,3.73603e-11*,4.35853e-11*,4.66978e-11*,4.98104e-11
M_112,0.000001*,0.000002*,0.000002*,0.000003*,0.000003
M_212,0.000001*,0.000002*,0.000002*,0.000002*,0.000003
M_312,0.000001*,0.000002*,0.000002*,0.000002*,0.000002
M_412,157.933629,234.885236,283.306660,476.820037,655.084705
M_512,607.935939,769.808735,863.438368,1200.86,1482.65
M_612,7.69998e-07*,0.000001*,0.000001*,0.000001*,0.000002
M_712,6.27154e-07*,9.40731e-07*,0.000001*,0.000001*,0.000001
M_812,531.327342,645.903711,710.583183,938.203703,1122.39
M_912,8.042869,17.700140,25.239675,63.461550,106.441334
M_1012,2.5984e-07*,3.89761e-07*,4.54721e-07*,4.87201e-07*,5.19681e-07
M_1112,7.95847e-08*,1.19377e-07*,1.39273e-07*,1.49221e-07*,1.59169e-07
M_1312,0.123267,0.520734,0.963605,4.260354,9.117882
M_1412,1.31281e-07*,1.96921e-07*,2.29741e-07*,2.46151e-07*,2.62561e-07
M_113,8.57775e-10*,1.28666e-09*,1.5011e-09*,1.60832e-09*,1.71554e-09
M_213,420.218631,549.506373,625.516874,905.842995,1143.66
M_313,311.216112,415.662459,477.881331,709.737254,909.554903
M_413,6.35875e-10*,9.53808e-10*,1.11277e-09*,1.19226e-09*,1.27174e-09
M_513,5.81788e-10*,8.72677e-10*,1.01812e-09*,1.09084e-09*,1.16357e-09
M_613,11.676818,25.697460,36.643526,92.134899,154.533912
M_713,4.06303e-10*,6.09449e-10*,7.11022e-10*,7.61809e-10*,8.12595e-10
M_813,3.39394e-10*,5.09086e-10*,5.93932e-10*,6.36355e-10*,6.78778e-10
M_913,2.52051e-10*,3.78072e-10*,4.41082e-10*,4.72587e-10*,5.04093e-10
M_1013,295.224321,349.669643,380.017823,484.944950,568.518486
M_1113,8.37744e-11*,1.25657e-10*,1.46598e-10*,1.57068e-10*,1.67539e-10
M_1213,12.734006,17.464512,20.317849,31.160901,40.653536
M_1413,134.559281,151.821732,161.241474,192.696985,216.776721
M_114,27.955654,49.670515,64.684346,131.646092,199.662353
M_214,1.18629e-09*,1.77943e-09*,2.076e-09*,2.22428e-09*,2.37257e-09
M_314,44.056644,70.109883,87.144213,158.123758,225.852332
M_414,9.56221e-10*,1.43433e-09*,1.67338e-09*,1.7929e-09*,1.91243e-09
M_514,8.71488e-10*,1.30723e-09*,1.5251e-09*,1.63403e-09*,1.74297e-09
M_614,7.43577e-10*,1.11536e-09*,1.30125e-09*,1.3942e-09*,1.48714e-09
M_714,6.25763e-10*,9.3864e-10*,1.09508e-09*,1.1733e-09*,1.25152e-09
M_814,33.923046,50.451717,60.852302,102.495614,140.707643
M_914,0.292965,1.237612,2.290167,10.125439,21.670162
M_1014,13.318457,21.194430,26.343959,47.801290,68.275843
M_1114,1.74001e-10*,2.60996e-10*,3.04493e-10*,3.26242e-10*,3.47991e-10
M_1214,138.939486,155.632244,164.665164,194.710567,217.710840
M_1314,5.67113e-11*,8.5062e-11*,9.92373e-11*,1.06325e-10*,1.13413e-10

In [18]:
#This cell must be executed once
#upper percentiles csv
upper_percentiles_filename = 'upper_percentiles'
index_3 = 0

while os.path.exists(f"{upper_percentiles_filename}{index_3}.csv"):
    index_3 += 1

with open('outfile-cortado.txt', 'r') as origin_file:
    for line in islice(origin_file, range_upper_start, range_upper_end):
        with open(f"{upper_percentiles_filename}{index_3}.csv", 'a') as upper_file:
            print(re.sub("\s+", ",", line.strip()))
            upper_file.write(re.sub("\s+", ",", line.strip()) + '\n')

M_21,224.517847,249.695601,288.972899,302.534364,330.260948
M_31,9.94854e-11,3.473987,20.682342,29.374089,50.723553
M_41,397.317557,473.169409,598.541123,643.204110,736.883073
M_51,2.0153e-10,7.041866,41.923666,59.542072,102.818012
M_61,2.68194e-10,9.372825,55.801007,79.251360,136.852264
M_71,253.437138,337.743676,488.029244,544.615703,666.696806
M_81,3.78424e-10,13.226461,78.743581,111.835543,193.119049
M_91,680.030551,835.845272,1097.71,1192.87,1393.54
M_101,4.87483e-10,17.031109,101.394512,144.005520,248.670578
M_111,5.64964e-10,19.741717,117.532085,166.924903,288.248062
M_121,5.99172e-10,20.933732,124.628729,177.003909,305.652618
M_131,6.26071e-10,21.880812,130.267158,185.011886,319.480896
M_141,705.845978,901.433265,1239.93,1365.16,1631.96
M_12,200.998563,227.223409,268.812306,283.274953,313.034498
M_32,183.670673,216.339931,269.890570,288.902108,328.602737
M_42,7.71149e-08,6.188677,36.844219,52.327989,90.360642
M_52,30.377207,55.668491,110.806630,133.714383,186.220018
M_62,1.20962e-07,9.707569,57.793900,82.081766,141.739845
M_72,1.53157e-07,12.287546,73.153759,103.896600,179.409981
M_82,1.78759e-07,14.344995,85.402760,121.293240,209.450722
M_92,2.12181e-07,17.031110,101.394512,144.005520,248.670578
M_102,2.35944e-07,18.933434,112.719978,160.090509,276.446343
M_112,2.76571e-07,22.191062,132.114230,187.635189,324.010849
M_122,2.94508e-07,23.628011,140.669088,199.785224,344.991684
M_132,3.08613e-07,24.771039,147.474089,209.450024,361.680985
M_142,3.24097e-07,26.012040,154.862376,219.943235,379.800797
M_13,1126.52,1243.4,1425.73,1488.47,1616.13
M_23,1.70237e-10,3.547467,21.119806,29.995397,51.796436
M_43,278.534904,333.997568,425.669017,458.541274,527.456609
M_53,334.050091,400.567098,510.509714,549.933787,632.584736
M_63,1019.6,1166.42,1401.17,1483.65,1653.4
M_73,6.31568e-10,13.169309,78.403331,111.352303,192.284584
M_83,7.65551e-10,15.961562,95.026975,134.962029,233.054161
M_93,9.40449e-10,19.611086,116.754371,165.820355,286.340714
M_103,1.0648e-09,22.199227,132.162837,187.704223,324.130058
M_113,1.2774e-09,26.632540,158.556519,225.189840,388.860703
M_123,1.37127e-09,28.592016,170.222234,241.758069,417.470932
M_133,1.44508e-09,30.126939,179.360378,254.736515,439.882278
M_143,1.52611e-09,31.825151,189.470665,269.095646,464.677811
M_14,847.229130,942.238625,1090.45,1141.63,1246.26
M_24,17.317086,31.734847,63.167357,76.226343,106.158146
M_34,80.147474,100.838924,136.200501,149.177299,176.779792
M_54,37.938607,44.128081,54.107029,57.648683,64.975604
M_64,9.846296,18.044069,35.916233,43.341422,60.360301
M_74,9.79422e-10,2.690197,16.016055,22.746797,39.279461
M_84,1.62851e-09,4.474136,26.636717,37.830789,65.326691
M_94,2.22635e-09,6.117238,36.418906,51.723939,89.317560
M_104,2.70178e-09,7.421514,44.183898,62.752166,108.361244
M_114,3.32241e-09,9.127891,54.342792,77.180332,133.275986
M_124,3.76368e-09,10.340316,61.560954,87.431923,150.978565
M_134,4.51811e-09,12.414095,73.907169,104.966632,181.257725
M_144,4.85119e-09,13.332599,79.375474,112.732989,194.668770
M_15,424.524068,521.794843,685.270857,744.673603,869.949508
M_25,34.566925,63.346461,126.089423,152.156684,211.904058
M_35,86.016802,118.315628,177.381439,199.833576,248.680272
M_45,142.950614,158.763547,183.431722,191.949024,209.318831
M_65,351.215248,400.687633,479.793223,507.400119,564.459659
M_75,1.62251e-10,6.131526,36.503969,51.844749,89.526176
M_85,2.24073e-10,8.470650,50.429917,71.623072,123.679638
M_95,3.04774e-10,11.520084,68.584687,97.407377,168.204308
M_105,3.62154e-10,13.691836,81.514188,115.770497,199.913979
M_115,4.60259e-10,17.406676,103.630441,147.181097,254.154205
M_125,5.03567e-10,19.039572,113.351870,160.987955,277.996063
M_135,5.37616e-10,20.329560,121.031800,171.895372,296.831131
M_145,5.75006e-10,21.742016,129.440837,183.838303,317.454338
M_16,6.19917e-11,3.016776,17.960341,25.508169,44.047832
M_26,79.972534,102.132624,140.484355,154.673082,184.901699
M_36,3.90423e-11,1.898242,11.301162,16.050471,27.716160
M_46,74.542510,87.017019,107.296092,114.470686,129.386846
M_56,13.205665,18.164318,27.232352,30.679299,38.178451
M_76,1.42686e-11,0.690919,4.113380,5.842026,10.088086
M_86,21.835685,30.034862,45.028938,50.728496,63.128412
M_96,4.02573e-11,1.957435,11.653564,16.550970,28.580427
M_106,5.07196e-11,2.467715,14.691511,20.865613,36.031008
M_116,14.697096,26.933521,53.610447,64.693673,90.096941
M_126,7.64716e-11,3.725045,22.177012,31.496893,54.389238
M_136,8.26854e-11,4.027131,23.975476,34.051161,58.799982
M_146,8.95021e-11,4.359833,25.956217,36.864309,63.657761
M_17,328.684074,473.929391,746.468358,852.320680,1084.43
M_27,4.28433e-09,22.060430,131.336515,186.530640,322.103500
M_37,2142.23,2427.13,2878.93,3036.58,3360.88
M_47,267.525247,336.591492,454.625339,497.940754,590.075457
M_57,1.87848e-09,9.674911,57.599471,81.805629,141.263008
M_67,122.490961,159.410631,224.119300,248.176250,299.888253
M_87,470.812550,532.240783,629.657274,663.534111,733.241909
M_97,1.65118e-09,8.503308,50.624345,71.899209,124.156475
M_107,629.953468,760.520022,978.130945,1056.43,1220.9
M_117,3.45236e-09,17.782242,105.866369,150.356675,259.637833
M_127,3.95412e-09,20.362218,121.226228,172.171509,297.307968
M_137,4.34866e-09,22.403339,133.378016,189.430080,327.110291
M_147,4.7818e-09,24.624078,146.599160,208.207406,359.535217
M_18,6.68078e-10,3.639318,21.666636,30.772033,53.137541
M_28,6.01996e-10,3.278040,19.515770,27.717266,47.862530
M_38,4.92546e-10,2.682032,15.967448,22.677763,39.160252
M_48,2.95329e-10,1.608403,9.575608,13.599754,23.484230
M_58,82.366352,100.312633,130.223100,141.055346,163.854527
M_68,1.94655e-10,1.060362,6.312853,8.965828,15.482306
M_78,47.538536,54.549084,65.758844,69.697201,77.832892
M_98,16.188955,21.068424,29.620612,32.800086,39.634576
M_108,1.9259e-10,1.049136,6.246019,8.870906,15.318394
M_118,3.29404e-10,1.794145,10.681421,15.170284,26.196241
M_128,3.89808e-10,2.122765,12.637859,17.948914,30.994415
M_138,4.37305e-10,2.381988,14.181136,20.140753,34.779310
M_148,4.89448e-10,2.665703,15.870234,22.539694,38.921833
M_19,957.808022,1134.52,1424.18,1527.36,1743.29
M_29,2.9949e-09,13.283612,79.083831,112.318783,193.953514
M_39,197.986271,272.329006,408.281742,459.960191,572.391427
M_49,1.69224e-09,7.503159,44.669969,63.442509,109.553337
M_59,1.78096e-09,7.895054,47.003113,66.756154,115.275383
M_69,1.28762e-09,5.709014,33.988549,48.272224,83.357096
M_79,8.33196e-10,3.694428,21.994735,31.238014,53.942204
M_89,110.477309,133.375257,171.538503,185.269968,214.114227
M_109,19.637595,28.315438,44.598582,50.922847,64.790657
M_119,53.211536,76.725685,120.847741,137.984454,175.561737
M_129,1.16211e-09,5.151788,30.671111,43.560634,75.221062
M_139,1.36116e-09,6.035593,35.932835,51.033596,88.125467
M_149,184.973441,240.725787,338.442265,374.770633,452.860863
M_110,1.53142e-07,13.789810,82.097474,116.598909,201.344490
M_210,1008.28,1177.02,1451.32,1548.36,1750.12
M_310,1.21907e-07,10.973064,65.328008,92.782080,160.217285
M_410,276.311983,347.646675,469.557286,514.295374,609.456197
M_510,8.98459e-08,8.086919,48.145381,68.378460,118.076801
M_610,6.9143e-08,6.200924,36.917129,52.431540,90.539455
M_710,805.839264,893.749601,1030.89,1078.24,1174.81
M_810,27.152495,42.212055,71.980952,83.824520,110.233603
M_910,1.42395e-08,1.281824,7.631322,10.838383,18.715858
M_1110,2.43448e-08,2.192163,13.051019,18.535706,32.007694
M_1210,41.711485,60.143769,94.730188,108.163323,137.619423
M_1310,207.028687,249.938240,321.454163,347.186208,401.238838
M_1410,5.28235e-08,4.755811,28.313664,40.212472,69.439411
M_111,3.09913e-10,32.168059,191.512165,271.995086,469.684601
M_211,2.89403e-10,30.045294,178.874307,254.046172,438.690186
M_311,2.55399e-10,26.501909,157.778804,224.085292,386.953354
M_411,1.87233e-10,19.431467,115.685013,164.301600,283.718109
M_511,1.99423e-10,20.696962,123.219122,175.001915,302.195549
M_611,1.62854e-10,16.900478,100.616797,142.900972,246.763229
M_711,235.976162,324.583888,486.623431,548.218015,682.222718
M_811,187.021570,257.247121,385.670642,434.487081,540.691749
M_911,6.74464e-11,6.992879,41.632023,59.127866,102.102757
M_1011,194.203432,238.701070,313.485059,340.659530,397.968438
M_1211,1.8877e-11,1.948250,11.598881,16.473306,28.446317
M_1311,245.062707,288.651684,360.101656,385.467813,438.438400
M_1411,4.98104e-11,5.161994,30.731870,43.646927,75.370073
M_112,0.000003,0.001745*,0.003487*,0.006971*,0.013939*
M_212,0.000003,0.001636*,0.003269*,0.006535*,0.013068*
M_312,0.000002,0.001455*,0.002908*,0.005814*,0.011626*
M_412,655.084705,873.075881,1261.67,1407.98,1723.28
M_512,1482.65,1805.69,2344.1,2539.09,2949.49
M_612,0.000002,0.000964*,0.001926*,0.003851*,0.007701*
M_712,0.000001,0.000785*,0.001569*,0.003137*,0.006272*
M_812,1122.39,1329.47,1668.9,1789.81,2042.84
M_912,106.441334,165.476779,282.174753,328.603088,432.130148
M_1012,5.19681e-07,8.601282,51.207631,72.727621,125.586987
M_1112,1.59169e-07,2.635087,15.687957,22.280816,38.474798
M_1312,9.117882,16.709197,33.259206,40.135091,55.894939
M_1412,2.62561e-07,4.345546,25.871155,36.743499,63.449145
M_113,1.71554e-09,30.714781,182.860093,259.706983,448.465347
M_213,1143.66,1420.8,1890.46,2061.7,2424.41
M_313,909.554903,1144.37,1545.67,1692.94,2006.19
M_413,1.27174e-09,22.762576,135.516730,192.467589,332.355499
M_513,1.16357e-09,20.827594,123.996836,176.106463,304.102898
M_613,154.533912,240.242894,409.667626,477.073324,627.376228
M_713,8.12595e-10,14.540942,86.569332,122.950063,212.311745
M_813,6.78778e-10,12.148749,72.327437,102.723017,177.383423
M_913,5.04093e-10,9.021753,53.710899,76.282886,131.726265
M_1013,568.518486,661.269133,810.805891,863.878370,973.673906
M_1113,1.67539e-10,2.998406,17.850975,25.352841,43.779612
M_1213,40.653536,51.918479,71.414341,78.627091,93.993619
M_1413,216.776721,242.825568,283.796870,298.042124,327.142467
M_114,199.662353,287.893040,453.449499,517.750527,658.749443
M_214,2.37257e-09,14.255186,84.868081,120.533863,208.139420
M_314,225.852332,310.658616,465.746351,524.698410,652.954054
M_414,1.91243e-09,11.495591,68.438865,97.200274,167.846680
M_514,1.74297e-09,10.475030,62.362972,88.570989,152.945518
M_614,1.48714e-09,8.936026,53.200524,75.558026,130.474567
M_714,1.25152e-09,7.519488,44.767184,63.580577,109.791756
M_814,140.707643,187.514414,270.952572,302.369227,370.148339
M_914,21.670162,39.712183,79.046031,95.387715,132.843614
M_1014,68.275843,93.913039,140.796530,158.617916,197.389985
M_1114,3.47991e-10,2.091128,12.449506,17.681406,30.532479
M_1214,217.710840,242.409957,281.099051,294.436050,321.772582
M_1314,1.13413e-10,0.681224,4.055659,5.760048,9.946525

In [19]:
#lower percentiles dataframe
lower_df = pd.read_csv(f"{lower_percentiles_filename}{index_1}.csv",header=None)
lower_df.columns = ['Pairs','P1','P2','P3','P4','MLE']
lower_df

,Pairs,P1,P2,P3,P4,MLE
0,M_21,144.188036,161.211053,170.453597,201.181520,2.245178e+02
1,M_31,4.97477e-11*,7.46165e-11*,8.7051e-11*,9.32682e-11*,9.948540e-11
2,M_41,182.605054,223.807209,247.275161,329.915700,3.973176e+02
3,M_51,1.0077e-10*,1.5115e-10*,1.7634e-10*,1.88935e-10*,2.015300e-10
4,M_61,1.34102e-10*,2.01148e-10*,2.34671e-10*,2.51433e-10*,2.681940e-10
...,...,...,...,...,...,...
177,M_914,0.292965,1.237612,2.290167,10.125439,2.167016e+01
178,M_1014,13.318457,21.194430,26.343959,47.801290,6.827584e+01
179,M_1114,1.74001e-10*,2.60996e-10*,3.04493e-10*,3.26242e-10*,3.479910e-10
180,M_1214,138.939486,155.632244,164.665164,194.710567,2.177108e+02
181,M_1314,5.67113e-11*,8.5062e-11*,9.92373e-11*,1.06325e-10*,1.134130e-10

In [20]:
#upper percentiles dataframe
upper_df = pd.read_csv(f"{upper_percentiles_filename}{index_3}.csv",header=None)
upper_df.columns = ['Pairs','MLE','P5','P6','P7','P8']
upper_df

      Pairs           MLE          P5          P6          P7          P8
0      M_21  2.245178e+02  249.695601  288.972899  302.534364  330.260948
1      M_31  9.948540e-11    3.473987   20.682342   29.374089   50.723553
2      M_41  3.973176e+02  473.169409  598.541123  643.204110  736.883073
3      M_51  2.015300e-10    7.041866   41.923666   59.542072  102.818012
4      M_61  2.681940e-10    9.372825   55.801007   79.251360  136.852264
..      ...           ...         ...         ...         ...         ...
177   M_914  2.167016e+01   39.712183   79.046031   95.387715  132.843614
178  M_1014  6.827584e+01   93.913039  140.796530  158.617916  197.389985
179  M_1114  3.479910e-10    2.091128   12.449506   17.681406   30.532479
180  M_1214  2.177108e+02  242.409957  281.099051  294.436050  321.772582
181  M_1314  1.134130e-10    0.681224    4.055659    5.760048    9.946525

[182 rows x 6 columns]

In [21]:
#This code must be executed once
#Delete repeated columns
upper_df = upper_df.drop(['MLE'], axis=1)
upper_df = upper_df.drop(['Pairs'], axis=1)
upper_df

             P5          P6          P7          P8
0    249.695601  288.972899  302.534364  330.260948
1      3.473987   20.682342   29.374089   50.723553
2    473.169409  598.541123  643.204110  736.883073
3      7.041866   41.923666   59.542072  102.818012
4      9.372825   55.801007   79.251360  136.852264
..          ...         ...         ...         ...
177   39.712183   79.046031   95.387715  132.843614
178   93.913039  140.796530  158.617916  197.389985
179    2.091128   12.449506   17.681406   30.532479
180  242.409957  281.099051  294.436050  321.772582
181    0.681224    4.055659    5.760048    9.946525

[182 rows x 4 columns]

In [22]:
#percentiles dataframe
percentiles_df = pd.concat([lower_df, upper_df],axis=1)
percentiles_df

,Pairs,P1,P2,P3,P4,MLE,P5,P6,P7,P8
0,M_21,144.188036,161.211053,170.453597,201.181520,2.245178e+02,249.695601,288.972899,302.534364,330.260948
1,M_31,4.97477e-11*,7.46165e-11*,8.7051e-11*,9.32682e-11*,9.948540e-11,3.473987,20.682342,29.374089,50.723553
2,M_41,182.605054,223.807209,247.275161,329.915700,3.973176e+02,473.169409,598.541123,643.204110,736.883073
3,M_51,1.0077e-10*,1.5115e-10*,1.7634e-10*,1.88935e-10*,2.015300e-10,7.041866,41.923666,59.542072,102.818012
4,M_61,1.34102e-10*,2.01148e-10*,2.34671e-10*,2.51433e-10*,2.681940e-10,9.372825,55.801007,79.251360,136.852264
...,...,...,...,...,...,...,...,...,...,...
177,M_914,0.292965,1.237612,2.290167,10.125439,2.167016e+01,39.712183,79.046031,95.387715,132.843614
178,M_1014,13.318457,21.194430,26.343959,47.801290,6.827584e+01,93.913039,140.796530,158.617916,197.389985
179,M_1114,1.74001e-10*,2.60996e-10*,3.04493e-10*,3.26242e-10*,3.479910e-10,2.091128,12.449506,17.681406,30.532479
180,M_1214,138.939486,155.632244,164.665164,194.710567,2.177108e+02,242.409957,281.099051,294.436050,321.772582
181,M_1314,5.67113e-11*,8.5062e-11*,9.92373e-11*,1.06325e-10*,1.134130e-10,0.681224,4.055659,5.760048,9.946525

In [23]:
#Delete * from rows
percentiles_df['P1'] = percentiles_df['P1'].str.replace('*','')
percentiles_df['P2'] = percentiles_df['P2'].str.replace('*','')
percentiles_df['P3'] = percentiles_df['P3'].str.replace('*','')
percentiles_df['P4'] = percentiles_df['P4'].str.replace('*','')
percentiles_df['P5'] = percentiles_df['P5'].str.replace('*','')
percentiles_df['P6'] = percentiles_df['P6'].str.replace('*','')
percentiles_df['P7'] = percentiles_df['P7'].str.replace('*','')
percentiles_df['P8'] = percentiles_df['P8'].str.replace('*','')
percentiles_df

,Pairs,P1,P2,P3,P4,MLE,P5,P6,P7,P8
0,M_21,144.188036,161.211053,170.453597,201.181520,2.245178e+02,249.695601,288.972899,302.534364,330.260948
1,M_31,4.97477e-11,7.46165e-11,8.7051e-11,9.32682e-11,9.948540e-11,3.473987,20.682342,29.374089,50.723553
2,M_41,182.605054,223.807209,247.275161,329.915700,3.973176e+02,473.169409,598.541123,643.204110,736.883073
3,M_51,1.0077e-10,1.5115e-10,1.7634e-10,1.88935e-10,2.015300e-10,7.041866,41.923666,59.542072,102.818012
4,M_61,1.34102e-10,2.01148e-10,2.34671e-10,2.51433e-10,2.681940e-10,9.372825,55.801007,79.251360,136.852264
...,...,...,...,...,...,...,...,...,...,...
177,M_914,0.292965,1.237612,2.290167,10.125439,2.167016e+01,39.712183,79.046031,95.387715,132.843614
178,M_1014,13.318457,21.194430,26.343959,47.801290,6.827584e+01,93.913039,140.796530,158.617916,197.389985
179,M_1114,1.74001e-10,2.60996e-10,3.04493e-10,3.26242e-10,3.479910e-10,2.091128,12.449506,17.681406,30.532479
180,M_1214,138.939486,155.632244,164.665164,194.710567,2.177108e+02,242.409957,281.099051,294.436050,321.772582
181,M_1314,5.67113e-11,8.5062e-11,9.92373e-11,1.06325e-10,1.134130e-10,0.681224,4.055659,5.760048,9.946525

In [24]:
#Change data types object -> numeric
percentiles_df['P1'] = pd.to_numeric(percentiles_df['P1'], errors = 'coerce')
percentiles_df['P2'] = pd.to_numeric(percentiles_df['P2'], errors = 'coerce')
percentiles_df['P3'] = pd.to_numeric(percentiles_df['P3'], errors = 'coerce')
percentiles_df['P4'] = pd.to_numeric(percentiles_df['P4'], errors = 'coerce')
percentiles_df['P5'] = pd.to_numeric(percentiles_df['P5'], errors = 'coerce')
percentiles_df['P6'] = pd.to_numeric(percentiles_df['P6'], errors = 'coerce')
percentiles_df['P7'] = pd.to_numeric(percentiles_df['P7'], errors = 'coerce')
percentiles_df['P8'] = pd.to_numeric(percentiles_df['P8'], errors = 'coerce')
percentiles_df['MLE'] = pd.to_numeric(percentiles_df['MLE'], errors = 'coerce')
percentiles_df

,Pairs,P1,P2,P3,P4,MLE,P5,P6,P7,P8
0,M_21,1.441880e+02,1.612111e+02,1.704536e+02,2.011815e+02,2.245178e+02,249.695601,288.972899,302.534364,330.260948
1,M_31,4.974770e-11,7.461650e-11,8.705100e-11,9.326820e-11,9.948540e-11,3.473987,20.682342,29.374089,50.723553
2,M_41,1.826051e+02,2.238072e+02,2.472752e+02,3.299157e+02,3.973176e+02,473.169409,598.541123,643.204110,736.883073
3,M_51,1.007700e-10,1.511500e-10,1.763400e-10,1.889350e-10,2.015300e-10,7.041866,41.923666,59.542072,102.818012
4,M_61,1.341020e-10,2.011480e-10,2.346710e-10,2.514330e-10,2.681940e-10,9.372825,55.801007,79.251360,136.852264
...,...,...,...,...,...,...,...,...,...,...
177,M_914,2.929650e-01,1.237612e+00,2.290167e+00,1.012544e+01,2.167016e+01,39.712183,79.046031,95.387715,132.843614
178,M_1014,1.331846e+01,2.119443e+01,2.634396e+01,4.780129e+01,6.827584e+01,93.913039,140.796530,158.617916,197.389985
179,M_1114,1.740010e-10,2.609960e-10,3.044930e-10,3.262420e-10,3.479910e-10,2.091128,12.449506,17.681406,30.532479
180,M_1214,1.389395e+02,1.556322e+02,1.646652e+02,1.947106e+02,2.177108e+02,242.409957,281.099051,294.436050,321.772582
181,M_1314,5.671130e-11,8.506200e-11,9.923730e-11,1.063250e-10,1.134130e-10,0.681224,4.055659,5.760048,9.946525

In [25]:
#Get the sum of significant percentiles rows
mixed_percentiles = percentiles_df[['Pairs','P3','MLE','P6']]
mixed_percentiles['Sum_of_values_1'] = mixed_percentiles.sum(axis=1)
mixed_percentiles

<ipython-input-25-2fc8867176d3>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mixed_percentiles['Sum_of_values_1'] = mixed_percentiles.sum(axis=1)

      Pairs            P3           MLE          P6  Sum_of_values_1
0      M_21  1.704536e+02  2.245178e+02  288.972899       683.944343
1      M_31  8.705100e-11  9.948540e-11   20.682342        20.682342
2      M_41  2.472752e+02  3.973176e+02  598.541123      1243.133841
3      M_51  1.763400e-10  2.015300e-10   41.923666        41.923666
4      M_61  2.346710e-10  2.681940e-10   55.801007        55.801007
..      ...           ...           ...         ...              ...
177   M_914  2.290167e+00  2.167016e+01   79.046031       103.006360
178  M_1014  2.634396e+01  6.827584e+01  140.796530       235.416332
179  M_1114  3.044930e-10  3.479910e-10   12.449506        12.449506
180  M_1214  1.646652e+02  2.177108e+02  281.099051       663.475055
181  M_1314  9.923730e-11  1.134130e-10    4.055659         4.055659

[182 rows x 5 columns]

In [26]:
mixed_percentiles['Sum_of_values_2'] = mixed_percentiles['Sum_of_values_1']
mixed_percentiles

<ipython-input-26-788d49ac2a10>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mixed_percentiles['Sum_of_values_2'] = mixed_percentiles['Sum_of_values_1']

,Pairs,P3,MLE,P6,Sum_of_values_1,Sum_of_values_2
0,M_21,1.704536e+02,2.245178e+02,288.972899,683.944343,683.944343
1,M_31,8.705100e-11,9.948540e-11,20.682342,20.682342,20.682342
2,M_41,2.472752e+02,3.973176e+02,598.541123,1243.133841,1243.133841
3,M_51,1.763400e-10,2.015300e-10,41.923666,41.923666,41.923666
4,M_61,2.346710e-10,2.681940e-10,55.801007,55.801007,55.801007
...,...,...,...,...,...,...
177,M_914,2.290167e+00,2.167016e+01,79.046031,103.006360,103.006360
178,M_1014,2.634396e+01,6.827584e+01,140.796530,235.416332,235.416332
179,M_1114,3.044930e-10,3.479910e-10,12.449506,12.449506,12.449506
180,M_1214,1.646652e+02,2.177108e+02,281.099051,663.475055,663.475055
181,M_1314,9.923730e-11,1.134130e-10,4.055659,4.055659,4.055659

In [27]:
#Get pair's first element (total)
first_element = list(combinations((total_per_group),len(total_per_group)-1))
print(first_element)

[(60, 32, 64, 38, 42, 56, 36, 54, 16, 56, 16, 16, 46), (60, 32, 64, 38, 42, 56, 36, 54, 16, 56, 16, 16, 34), (60, 32, 64, 38, 42, 56, 36, 54, 16, 56, 16, 46, 34), (60, 32, 64, 38, 42, 56, 36, 54, 16, 56, 16, 46, 34), (60, 32, 64, 38, 42, 56, 36, 54, 16, 16, 16, 46, 34), (60, 32, 64, 38, 42, 56, 36, 54, 56, 16, 16, 46, 34), (60, 32, 64, 38, 42, 56, 36, 16, 56, 16, 16, 46, 34), (60, 32, 64, 38, 42, 56, 54, 16, 56, 16, 16, 46, 34), (60, 32, 64, 38, 42, 36, 54, 16, 56, 16, 16, 46, 34), (60, 32, 64, 38, 56, 36, 54, 16, 56, 16, 16, 46, 34), (60, 32, 64, 42, 56, 36, 54, 16, 56, 16, 16, 46, 34), (60, 32, 38, 42, 56, 36, 54, 16, 56, 16, 16, 46, 34), (60, 64, 38, 42, 56, 36, 54, 16, 56, 16, 16, 46, 34), (32, 64, 38, 42, 56, 36, 54, 16, 56, 16, 16, 46, 34)]

In [28]:
#Reverse the list 
first_element.reverse()
print(first_element)

[(32, 64, 38, 42, 56, 36, 54, 16, 56, 16, 16, 46, 34), (60, 64, 38, 42, 56, 36, 54, 16, 56, 16, 16, 46, 34), (60, 32, 38, 42, 56, 36, 54, 16, 56, 16, 16, 46, 34), (60, 32, 64, 42, 56, 36, 54, 16, 56, 16, 16, 46, 34), (60, 32, 64, 38, 56, 36, 54, 16, 56, 16, 16, 46, 34), (60, 32, 64, 38, 42, 36, 54, 16, 56, 16, 16, 46, 34), (60, 32, 64, 38, 42, 56, 54, 16, 56, 16, 16, 46, 34), (60, 32, 64, 38, 42, 56, 36, 16, 56, 16, 16, 46, 34), (60, 32, 64, 38, 42, 56, 36, 54, 56, 16, 16, 46, 34), (60, 32, 64, 38, 42, 56, 36, 54, 16, 16, 16, 46, 34), (60, 32, 64, 38, 42, 56, 36, 54, 16, 56, 16, 46, 34), (60, 32, 64, 38, 42, 56, 36, 54, 16, 56, 16, 46, 34), (60, 32, 64, 38, 42, 56, 36, 54, 16, 56, 16, 16, 34), (60, 32, 64, 38, 42, 56, 36, 54, 16, 56, 16, 16, 46)]

In [31]:
#Create list of tuples, first_elements returns a list of tuples
first_element_list = []

for tuple_element in first_element:
    for list_element in tuple_element:
        first_element_list.append(list_element)
        
print(first_element_list, len(first_element_list))

[32, 64, 38, 42, 56, 36, 54, 16, 56, 16, 16, 46, 34, 60, 64, 38, 42, 56, 36, 54, 16, 56, 16, 16, 46, 34, 60, 32, 38, 42, 56, 36, 54, 16, 56, 16, 16, 46, 34, 60, 32, 64, 42, 56, 36, 54, 16, 56, 16, 16, 46, 34, 60, 32, 64, 38, 56, 36, 54, 16, 56, 16, 16, 46, 34, 60, 32, 64, 38, 42, 36, 54, 16, 56, 16, 16, 46, 34, 60, 32, 64, 38, 42, 56, 54, 16, 56, 16, 16, 46, 34, 60, 32, 64, 38, 42, 56, 36, 16, 56, 16, 16, 46, 34, 60, 32, 64, 38, 42, 56, 36, 54, 56, 16, 16, 46, 34, 60, 32, 64, 38, 42, 56, 36, 54, 16, 16, 16, 46, 34, 60, 32, 64, 38, 42, 56, 36, 54, 16, 56, 16, 46, 34, 60, 32, 64, 38, 42, 56, 36, 54, 16, 56, 16, 46, 34, 60, 32, 64, 38, 42, 56, 36, 54, 16, 56, 16, 16, 34, 60, 32, 64, 38, 42, 56, 36, 54, 16, 56, 16, 16, 46] 182

In [32]:
mixed_percentiles['First_total'] = first_element_list
mixed_percentiles

<ipython-input-32-5c7112a3f319>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mixed_percentiles['First_total'] = first_element_list

,Pairs,P3,MLE,P6,Sum_of_values_1,Sum_of_values_2,First_total
0,M_21,1.704536e+02,2.245178e+02,288.972899,683.944343,683.944343,32
1,M_31,8.705100e-11,9.948540e-11,20.682342,20.682342,20.682342,64
2,M_41,2.472752e+02,3.973176e+02,598.541123,1243.133841,1243.133841,38
3,M_51,1.763400e-10,2.015300e-10,41.923666,41.923666,41.923666,42
4,M_61,2.346710e-10,2.681940e-10,55.801007,55.801007,55.801007,56
...,...,...,...,...,...,...,...
177,M_914,2.290167e+00,2.167016e+01,79.046031,103.006360,103.006360,16
178,M_1014,2.634396e+01,6.827584e+01,140.796530,235.416332,235.416332,56
179,M_1114,3.044930e-10,3.479910e-10,12.449506,12.449506,12.449506,16
180,M_1214,1.646652e+02,2.177108e+02,281.099051,663.475055,663.475055,16
181,M_1314,9.923730e-11,1.134130e-10,4.055659,4.055659,4.055659,46

In [34]:
second_element_list = [element for element in total_per_group for i in range(len(total_per_group) -1)]
print(second_element_list)

[60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34]

In [35]:
mixed_percentiles['Second_total'] = second_element_list
mixed_percentiles

<ipython-input-35-9b3d4aca53bd>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mixed_percentiles['Second_total'] = second_element_list

,Pairs,P3,MLE,P6,Sum_of_values_1,Sum_of_values_2,First_total,Second_total
0,M_21,1.704536e+02,2.245178e+02,288.972899,683.944343,683.944343,32,60
1,M_31,8.705100e-11,9.948540e-11,20.682342,20.682342,20.682342,64,60
2,M_41,2.472752e+02,3.973176e+02,598.541123,1243.133841,1243.133841,38,60
3,M_51,1.763400e-10,2.015300e-10,41.923666,41.923666,41.923666,42,60
4,M_61,2.346710e-10,2.681940e-10,55.801007,55.801007,55.801007,56,60
...,...,...,...,...,...,...,...,...
177,M_914,2.290167e+00,2.167016e+01,79.046031,103.006360,103.006360,16,34
178,M_1014,2.634396e+01,6.827584e+01,140.796530,235.416332,235.416332,56,34
179,M_1114,3.044930e-10,3.479910e-10,12.449506,12.449506,12.449506,16,34
180,M_1214,1.646652e+02,2.177108e+02,281.099051,663.475055,663.475055,16,34
181,M_1314,9.923730e-11,1.134130e-10,4.055659,4.055659,4.055659,46,34